package lexico;

public enum TipoToken {
	OPMAIOR, OPMENOR, OPIGUAL, OPIGUALIGUAL,OPMENORIGUAL,
	OPMAIORIGUAL, OPDIFERENTE, OPAND, OPOR,
        OPARITMAIS, OPARITMENOS, OPARITMULTIPLICACAO,
        OPARITDIVISAO, VALTRUE, VALFALSE, VALDIGITO,
        DECLARACAOVARINI, NOMEVAR, FINALIZAVAR, 
        TIPOVAR, EOF, ERRO, PROGRAMAINICIO, 
        PROGRAMAFIM, OUTRAVAR, DECLARACAOVARFIM ,DECLARACAOCONSTINI, 
        DECLARACAOSEINI, DECLARACAOSEFIM, FECHAMENTODETAG,
        DECLARACAOSENAOINI, DECLARACAOSENAOFIM,
        DECLARAENTAOINI, DECLARAENTAOFIM;
	
	
}
